"""Report writer — generates JSON and Markdown QC reports."""

from __future__ import annotations


from pattern_pilot.core.config import pp_now

from pattern_pilot.core.contracts import (
    ReviewRunResult,
)


class ReportWriter:
    """Generates human-readable and machine-readable reports."""

    def to_json(self, run_result: ReviewRunResult) -> str:
        """Serialize a full run result to JSON."""
        return run_result.model_dump_json(indent=2)

    def to_markdown(self, run_result: ReviewRunResult) -> str:
        """Generate a Markdown summary report."""
        lines: list[str] = []

        lines.append(f"# QC Report: {run_result.task_ref}")
        lines.append(f"**Project:** {run_result.project_name}")
        lines.append(f"**Run ID:** {run_result.run_id}")
        lines.append(f"**Status:** {run_result.status.value}")
        if run_result.verdict:
            lines.append(f"**Verdict:** {run_result.verdict.value}")
        lines.append(f"**Profile:** {run_result.review_profile.value}")
        lines.append(f"**Rounds:** {run_result.total_rounds}")
        lines.append("")

        # Findings summary
        if run_result.unresolved_findings:
            lines.append("## Unresolved Findings")
            lines.append("")
            for i, f in enumerate(run_result.unresolved_findings, 1):
                lines.append(f"### {i}. [{f.tier.value.upper()}] {f.category}")
                lines.append(f"- **File:** {f.file_path}")
                if f.line_start:
                    lines.append(f"- **Line:** {f.line_start}")
                lines.append(f"- **Message:** {f.message}")
                if f.suggestion:
                    lines.append(f"- **Suggestion:** {f.suggestion}")
                lines.append(f"- **Autofix safe:** {'Yes' if f.autofix_safe else 'No'}")
                lines.append("")

        if run_result.advisories:
            lines.append("## Advisories")
            lines.append("")
            for i, a in enumerate(run_result.advisories, 1):
                lines.append(f"{i}. **[{a.category}]** {a.message}")
            lines.append("")

        # Round details
        if run_result.rounds:
            lines.append("## Round History")
            lines.append("")
            for rnd in run_result.rounds:
                cost = f"${rnd.cost_usd:.4f}" if rnd.cost_usd is not None else "cost n/a"
                lines.append(
                    f"- **Round {rnd.round_number}:** {rnd.verdict.value} "
                    f"({len(rnd.findings)} findings, {rnd.duration_ms}ms, "
                    f"{cost})"
                )
            lines.append("")

        lines.append("---")
        lines.append(f"*Generated by Pattern Pilot at {pp_now().isoformat()}*")

        return "\n".join(lines)

    def summary_for_mcp(self, run_result: ReviewRunResult) -> str:
        """Short summary suitable for MCP response."""
        parts: list[str] = []

        verdict_str = run_result.verdict.value if run_result.verdict else "unknown"
        parts.append(f"Verdict: {verdict_str} (round {run_result.total_rounds})")

        blocking = [f for f in run_result.unresolved_findings if f.tier.value == "blocking"]
        autofix = [
            f for f in run_result.unresolved_findings if f.tier.value == "recommended_autofix"
        ]

        if blocking:
            parts.append(f"  {len(blocking)} blocking finding(s)")
        if autofix:
            parts.append(f"  {len(autofix)} recommended autofix(es)")
        if run_result.advisories:
            parts.append(f"  {len(run_result.advisories)} advisory(ies) logged")

        return "\n".join(parts)
