"""add_severity_confidence_rule_refs_why_now_to_findings

Revision ID: 163f7bcf6796
Revises: 1bd8fa731a4c
Create Date: 2026-03-26 16:07:28.775336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '163f7bcf6796'
down_revision: Union[str, None] = '1bd8fa731a4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add with server_default so existing rows get a value, then drop the default
    op.add_column('findings', sa.Column(
        'severity', sa.String(length=20), nullable=False,
        server_default='medium',
    ))
    op.add_column('findings', sa.Column(
        'confidence', sa.Float(), nullable=False,
        server_default='0.8',
    ))
    op.add_column('findings', sa.Column(
        'rule_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False,
        server_default='[]',
    ))
    op.add_column('findings', sa.Column('why_now', sa.Text(), nullable=True))

    # Drop server defaults — the ORM handles defaults going forward
    op.alter_column('findings', 'severity', server_default=None)
    op.alter_column('findings', 'confidence', server_default=None)
    op.alter_column('findings', 'rule_refs', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('findings', 'why_now')
    op.drop_column('findings', 'rule_refs')
    op.drop_column('findings', 'confidence')
    op.drop_column('findings', 'severity')
    # ### end Alembic commands ###
