"""initial_schema

Revision ID: 1bd8fa731a4c
Revises: 
Create Date: 2026-03-26 13:52:09.597003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1bd8fa731a4c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('repo_path', sa.Text(), nullable=False),
    sa.Column('connector_type', sa.String(length=50), nullable=False),
    sa.Column('connector_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('governance_paths', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('completion_gates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tech_stack', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=True)
    op.create_table('review_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('task_ref', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('verdict', sa.String(length=50), nullable=True),
    sa.Column('review_profile', sa.String(length=20), nullable=False),
    sa.Column('governance_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('diff_hash', sa.String(length=64), nullable=True),
    sa.Column('task_title_snapshot', sa.Text(), nullable=True),
    sa.Column('task_status_snapshot', sa.String(length=50), nullable=True),
    sa.Column('project_context_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('connector_type', sa.String(length=50), nullable=False),
    sa.Column('connector_capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_submissions', sa.Integer(), nullable=False),
    sa.Column('total_rounds', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_runs_task_ref'), 'review_runs', ['task_ref'], unique=False)
    op.create_table('event_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['review_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_rounds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('verdict', sa.String(length=50), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['review_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_submissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('submission_number', sa.Integer(), nullable=False),
    sa.Column('diff_hash', sa.String(length=64), nullable=False),
    sa.Column('files_changed', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deterministic_results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deterministic_passed', sa.Boolean(), nullable=False),
    sa.Column('progressed_to_llm', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['review_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('round_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('tier', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('line_start', sa.Integer(), nullable=True),
    sa.Column('line_end', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('autofix_safe', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('human_override', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['review_rounds.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['review_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advisories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('task_ref', sa.String(length=255), nullable=False),
    sa.Column('finding_id', sa.String(length=36), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('advisories')
    op.drop_table('findings')
    op.drop_table('review_submissions')
    op.drop_table('review_rounds')
    op.drop_table('event_log')
    op.drop_index(op.f('ix_review_runs_task_ref'), table_name='review_runs')
    op.drop_table('review_runs')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
